### ISSUE TITLE
The SUSE Studio Express page does not allow to build anything

### ISSUE THREAD

**Issue by yecril71pl** [openSUSE/studioexpress-landing#2]
The [SUSE Studio Express page](https://studioexpress.opensuse.org/) does not allow to build anything.
Ping from [Bug 1188047](https://bugzilla.suse.com/show_bug.cgi?id=1188047#c1).

**Comment by hennevogel** [comment]
Please read the content of the page...

**Comment by yecril71pl** [comment]
I have.  It says:
> This is the new home for building

**Comment by hennevogel** [comment]
It also says:

> export

What is the point of this conversation? 😃

**Comment by yecril71pl** [comment]
The point is that it says it does something that it does not do, which is a bug.  *This*, when placed on a page, refers to the page it is on.

**Comment by hennevogel** [comment]
Again, please read the content of the page. It explains how and where you can build images now.
